CyberGate
rust-gamedev/rust-gamedev.github.io pull request #1100
Opened 2022-07-29 19:33 UTC by cybersoulK

Part of #1098

2022-07-30 11:48 UTC, 17cupsofcoffee requested changes
The general content of this post looks okay, but there's a lot of issues;

* You've created a new file, rather than adding to [the existing one](https://github.com/rust-gamedev/rust-gamedev.github.io/blob/source/content/news/036/index.md).
* The links are not formatted correctly (if you look at the [preview](https://github.com/rust-gamedev/rust-gamedev.github.io/blob/258c79fc4cd732277a76a5f4d3c4cb9bc6a8161a/content/posts/newsletter-036/index.md) they're all showing up with extra markup.
* There's quite a few formatting issues (extra new lines in the list, placeholder brackets left in the initial description, etc)

Could you please update this PR/resubmit to resolve these issues and move your content to the right file?

2022-07-31 19:35 UTC, cybersoulK commented
is everything good now? @17cupsofcoffee

2022-08-02 17:42 UTC, ozkriff commented
:construction:

2022-08-02 18:14 UTC, ozkriff approved these changes
Fixed the formatting, made a few style tweaks  to fit with the rest of the newsletter, and reduced the image size

2022-08-02 18:15 UTC, ozkriff commented
I've rephrased a few things. @cybersoulK are you ok with my changes?

2022-08-02 19:42 UTC, 17cupsofcoffee approved these changes

2022-08-02 19:42 UTC, 17cupsofcoffee commented on content/news/036/index.md
> +is a new multiplayer project that aims at procedurally generating destinct
```suggestion
is a new multiplayer project that aims at procedurally generating distinct
```

2022-08-02 19:42 UTC, 17cupsofcoffee commented on content/news/036/index.md
> +Please, [join our Discord server][cybergate-dis] to participate in tests.
```suggestion
[Join the Discord server][cybergate-dis] to participate in tests.
```

2022-08-06 19:27 UTC, merged

2022-08-06 19:27 UTC, ozkriff commented
Thanks for the PR!