N37: Cybergate
rust-gamedev/rust-gamedev.github.io pull request #1140
Opened 2022-09-05 00:10 UTC by cybersoulK

Part of #1134

2022-09-05 19:41 UTC, cybersoulK commented
i am not sure if the last 3 bullet points are necessary. 
Feel free to remove and change what may be necessary

2022-09-06 17:48 UTC, 17cupsofcoffee approved these changes
lgtm, just one bit i'm not sure about

2022-09-06 17:48 UTC, 17cupsofcoffee commented on content/news/037/index.md
> +- Unreliable protocol archieved with WebRTC
Is this meant to say 'achieved'?

2022-09-06 19:02 UTC, cybersoulK commented on content/news/037/index.md
> +- Unreliable protocol archieved with WebRTC
yep achieved. my bad

2022-09-07 10:38 UTC, ozkriff requested changes
lgtm expect for the image size

> Only include one image (<300kb) or GIF (<2.5mb). 

Could you optimize it a little, please?

2022-09-08 11:14 UTC, ozkriff approved these changes
:rocket:

2022-09-08 23:04 UTC, merged