N43 hexx
rust-gamedev/rust-gamedev.github.io pull request #1292
Opened 2023-03-02 08:17 UTC by ManevilleF

_Part of #1287 _

2023-03-02 14:29 UTC, AngelOnFira requested changes

2023-03-02 14:29 UTC, AngelOnFira commented on content/news/043/index.md
> +An hexagonal tools library made by [@ManevilleF](https://linktr.ee/ManevilleF):
If we can move the links to the bottom, that would be better :)

2023-03-02 14:29 UTC, AngelOnFira commented on content/news/043/index.md
> +_Discussions: [Twitter](https://twitter.com/ManevilleF/status/1625159292490854400)
Here as well for moving links

2023-03-02 14:30 UTC, AngelOnFira commented
Also, if we can reduce image sizes as well, converting to jpg should work alright :)

2023-03-04 14:53 UTC, ozkriff approved these changes

2023-03-04 14:54 UTC, merged

2023-03-04 14:55 UTC, ozkriff commented
Merged, thanks for the PR!

Great lib, btw - I'll probably migrate Zemeroth to it once I return to development :D