N49: Oort
rust-gamedev/rust-gamedev.github.io pull request #1446
Opened 2023-09-15 05:58 UTC by rlane

_Part of #1440_

2023-10-04 22:42 UTC, AngelOnFira requested changes

2023-10-04 22:42 UTC, AngelOnFira commented on content/news/049/index.md
> +
All links to the bottom please!

2023-10-05 01:51 UTC, rlane commented on content/news/049/index.md
> +
Done.

2023-10-05 16:08 UTC, ozkriff approved these changes

2023-10-05 16:08 UTC, merged

2023-10-05 16:08 UTC, ozkriff commented
Thanks (and sorry for the super-late review)!