space_editor section in August 2023
rust-gamedev/rust-gamedev.github.io pull request #1448
Opened 2023-09-15 19:28 UTC by rewin123

_Part of #1440

2023-10-04 22:44 UTC, AngelOnFira requested changes

2023-10-04 22:44 UTC, AngelOnFira commented on content/news/049/space_editor.png
If we could convert this to a PNG, that would be great! :)

2023-10-04 22:44 UTC, AngelOnFira commented on content/news/049/index.md
> +Link to project: https://github.com/rewin123/space_editor
```suggestion
The [Github project][space_editor] is free for use 
and open to contribute for everyone, be it with suggestions, bugs or PRs.

[space_editor]: https://github.com/rewin123/space_editor
```

2023-10-05 12:01 UTC, rewin123 commented on content/news/049/space_editor.png
I don't understand the question a little bit. Isn't the image already in png format? 😅

2023-10-05 16:33 UTC, ozkriff approved these changes

2023-10-05 16:34 UTC, merged

2023-10-05 16:34 UTC, ozkriff commented
Thanks for the PR (and sorry for the late review)!