N49: Ars Militaris
rust-gamedev/rust-gamedev.github.io pull request #1450
Opened 2023-09-15 21:41 UTC by arsmilitaris

Hey! Thanks for mentioning Ars Militaris. I've added a section on it. Hope everything is alright.

Part of #1440

2023-10-05 02:23 UTC, AngelOnFira requested changes
We might need to shorten this into only a couple paragraphs but otherwise LGTM!

2023-10-05 02:23 UTC, AngelOnFira commented on content/news/049/index.md
> +being developed with Bevy Engine.
We put links at the bottom for cleanliness if you could switch that out :)
```
[This blog post][ars-militaris-blog-post]

...

[ars-militaris-blog-post]: https://example.com
```

2023-10-05 16:48 UTC, ozkriff commented
:construction: editing

2023-10-10 12:37 UTC, ozkriff approved these changes
:+1: (i've embedded the image and made a bunch of style/fmt tweaks for consistency with the rest of the newsletter)

2023-10-10 12:39 UTC, merged

2023-10-10 12:40 UTC, ozkriff commented
Thanks for the PR (and sorry for the delay)!