N49: nanogltf
rust-gamedev/rust-gamedev.github.io pull request #1451
Opened 2023-09-17 05:26 UTC by not-fl3

2023-10-05 02:25 UTC, AngelOnFira requested changes
Looks good after the gif size change :)

2023-10-05 02:25 UTC, AngelOnFira commented on content/news/049/helmet.gif
We'll want to get this down to 2.5MB likely

2023-10-14 15:53 UTC, ozkriff approved these changes
I've optimized the GIF and extended the description a bit based on social media posts, hope it's ok.

2023-10-14 15:53 UTC, merged

2023-10-14 15:54 UTC, ozkriff commented
Thanks for the PR, @not-fl3. Feel free to ping me if something is wrong with my additions!