Rust Gamedev Meetup 30 post
rust-gamedev/rust-gamedev.github.io pull request #1453
Opened 2023-09-23 17:43 UTC by AngelOnFira

I'm giving this a try, it might be a nice way to see the content from the meetup in a post that can be shared.

2023-09-23 17:43 UTC, AngelOnFira commented
@ElhamAryanpur @cybersoulK @kpreid do your sections look good?

2023-09-23 17:44 UTC, AngelOnFira commented
@scirin does this kind of post look good to you?

2023-09-23 17:47 UTC, ElhamAryanpur commented
> @ElhamAryanpur @cybersoulK @kpreid do your sections look good?

Fire as hell 🔥thanks for having us!

2023-09-23 17:47 UTC, scirin commented
This looks great!

2023-09-23 17:48 UTC, scirin approved these changes

2023-09-23 17:48 UTC, ElhamAryanpur commented
Oh this is interesting, first time I saw the talks section!

2023-09-23 23:38 UTC, kpreid requested changes

2023-09-23 23:38 UTC, kpreid commented on content/blog/rust-gamedev-meetup-30/index.md
> +> projects.
How about:

```
An introduction to making your Rust crates `no_std` compatible, and why you might want to do this.
```

2023-09-24 00:08 UTC, AngelOnFira commented on content/blog/rust-gamedev-meetup-30/index.md
> +> projects.
```suggestion
> An introduction to making your Rust crates `no_std` compatible, and
> why you might want to do this.
```

2023-09-24 00:08 UTC, AngelOnFira commented on content/blog/rust-gamedev-meetup-30/index.md
> +> projects.
Looks good!

2023-09-25 15:00 UTC, merged