Added short description of RustGameDev podcast, ep 2
rust-gamedev/rust-gamedev.github.io pull request #234
Opened 2020-08-29 18:13 UTC by icefoxen

Right now it's in the "Learning Material Updates" section because I didn't know where else to put it.  Do we really want it to have its own section?  No idea.

2020-09-02 13:54 UTC, 17cupsofcoffee reviewed
Content looks good! I agree that having this under learning material seems a bit weird though.

@ozkriff: Would a 'Community Updates' section (or something similar) make sense for things that aren't tied to one project in particular, but to the Rust gamedev community as a whole? Probably wouldn't have stuff to put there every month, though.

2020-09-02 13:54 UTC, 17cupsofcoffee commented on content/posts/newsletter-013/index.md
> +```
There's a stray code fence here, think that's the only thing keeping it from going green on CI:
```suggestion
```

2020-09-03 12:23 UTC, ozkriff requested changes
It's a nice overview of the second episode, but the first episode was released in August too, so it should be included.

Also, I think it makes sense to announce the podcast as a whole before speaking about individual episodes.

> Do we really want it to have its own section? No idea.

Yeah, this podcast seems like an important community-wide update and I usually put them in top-level sections.

2020-09-03 12:24 UTC, ozkriff commented
Oh, and the logo looks like a good fit for the section's image:

![image](https://user-images.githubusercontent.com/662976/92114488-92937b80-edf9-11ea-947d-803d0d74c8f0.png)

2020-09-07 14:48 UTC, ozkriff commented
Hijacking the PR

2020-09-07 16:22 UTC, ozkriff commented
@icefoxen @patchfx r?

2020-09-07 16:26 UTC, ozkriff approved these changes
Hijacked the PR: added some intro and 1st episode.

2020-09-07 17:18 UTC, icefoxen commented
Sorry for being out of the loop a bit.  Looks great to me, thanks!

2020-09-07 17:26 UTC, 17cupsofcoffee approved these changes

2020-09-07 17:26 UTC, merged