Newsletter 13: Egregoria
rust-gamedev/rust-gamedev.github.io pull request #235
Opened 2020-08-29 19:01 UTC by Uriopass

Part of #232

2020-08-29 19:24 UTC, 17cupsofcoffee requested changes
Looks good, but a few bits of trailing whitespace are tripping up the linter:

2020-08-29 19:24 UTC, 17cupsofcoffee commented on content/posts/newsletter-013/index.md
> +Egregoria was previously known as Scale,
```suggestion
Egregoria was previously known as Scale,
```

2020-08-29 19:24 UTC, 17cupsofcoffee commented on content/posts/newsletter-013/index.md
> +[/r/rust_gamedev](https://www.reddit.com/r/rust_gamedev/comments/igzbl9/egregoria_devblog_5/)
```suggestion
[/r/rust_gamedev](https://www.reddit.com/r/rust_gamedev/comments/igzbl9/egregoria_devblog_5/)
```

2020-08-29 19:33 UTC, Uriopass commented
Done ✔️

2020-08-30 00:02 UTC, 17cupsofcoffee approved these changes

2020-09-04 10:49 UTC, ozkriff approved these changes
:+1: (made a few small style/fmt tweaks for consistency)

2020-09-04 10:49 UTC, merged

2020-09-04 10:50 UTC, ozkriff commented
Merged, thanks for the PR!