Add blitz-path august content
rust-gamedev/rust-gamedev.github.io pull request #236
Opened 2020-08-29 19:20 UTC by BezPowell

Part of #232

2020-08-29 19:26 UTC, 17cupsofcoffee requested changes
Content looks good, just needs breaking onto more lines to satisfy the formatting CI checks:

2020-08-29 19:26 UTC, 17cupsofcoffee commented on content/posts/newsletter-013/index.md
> +[blitz-path](https://github.com/BezPowell/blitz-path) is a new crate providing an implementation of the [JPS](https://en.wikipedia.org/wiki/Jump_point_search) pathfinding algorithm.
```suggestion
[blitz-path](https://github.com/BezPowell/blitz-path) is a new crate providing
an implementation of the [JPS](https://en.wikipedia.org/wiki/Jump_point_search)
pathfinding algorithm.
```

2020-08-29 19:26 UTC, 17cupsofcoffee commented on content/posts/newsletter-013/index.md
> +JPS is an optimization of the A* search algorithm for uniform-cost grids, which are common in games. While fully functional, the code is still in an early state and any suggestions for improvements -
```suggestion
JPS is an optimization of the A* search algorithm for uniform-cost grids, which
are common in games. While fully functional, the code is still in an early
state and any suggestions for improvements - especially on how best to
integrate it with the existing ecosystem - are greatly appreciated.
```

2020-08-30 08:30 UTC, BezPowell commented
> Content looks good, just needs breaking onto more lines to satisfy the formatting CI checks:

Thanks for the suggestions, I have applied them now. Does the url of links get taken into account for the line-length?

2020-08-30 19:22 UTC, 17cupsofcoffee commented
They shouldn't do, I think it was a false positive because of there being trailing whitespace after the link.

2020-08-30 19:22 UTC, 17cupsofcoffee commented on content/posts/newsletter-013/index.md
> +### [blitz-path](https://github.com/BezPowell/blitz-path)
```suggestion
### [blitz-path](https://github.com/BezPowell/blitz-path)

```

2020-08-30 19:23 UTC, 17cupsofcoffee commented on content/posts/newsletter-013/index.md
> +### [blitz-path](https://github.com/BezPowell/blitz-path)
Linter is now complaining that there needs to be an extra linebreak here (why didn't it say that the first time 🤔)

2020-08-31 08:55 UTC, BezPowell commented
I'm terribly sorry, I seem to be making a lot of unnecessary work for you. I ran it through a linter provided by a VSCode extension originally and as it didn't complain assumed it was ok, it looks like it actually didn't report any errors because it wasn't working :laughing:

2020-08-31 12:44 UTC, 17cupsofcoffee commented
It's no problem at all, I don't know of an easy way of running the lint config locally so I also make mistakes in my own PRs 😅

2020-08-31 12:44 UTC, 17cupsofcoffee approved these changes

2020-09-04 11:02 UTC, ozkriff approved these changes
:+1:

2020-09-04 11:03 UTC, merged

2020-09-04 11:06 UTC, ozkriff commented
Thanks for the PR!

> It's no problem at all, I don't know of an easy way of running the lint config locally so I also make mistakes in my own PRs

@17cupsofcoffee I'm using https://marketplace.visualstudio.com/items?itemName=DavidAnson.vscode-markdownlint vscode extension to auto-run all the lints with our config file locally. I guess this (along with a style/formatting guide) should be documented in CONTRIBUTING.md or something.. :thinking: