Newsletter 12: add Mun
rust-gamedev/rust-gamedev.github.io pull request #250
Opened 2020-09-01 12:12 UTC by Wodann

2020-09-02 13:47 UTC, 17cupsofcoffee requested changes
Looks good for the most part, just one typo in the heading link.

2020-09-02 13:47 UTC, 17cupsofcoffee commented on content/posts/newsletter-013/index.md
> +### [This Month in Mun][mun-july]
```suggestion
### [This Month in Mun][mun-august]
```

2020-09-02 14:33 UTC, Wodann commented
Thanks for spotting that!

2020-09-02 14:36 UTC, 17cupsofcoffee approved these changes

2020-09-04 17:56 UTC, ozkriff approved these changes

2020-09-04 18:03 UTC, merged