N14: Add audir 0.1.0 section
rust-gamedev/rust-gamedev.github.io pull request #286
Opened 2020-10-02 17:12 UTC by msiglreith

#278

2020-10-02 19:56 UTC, 17cupsofcoffee requested changes
Content looks fine, just needs linter errors fixing (due to lines being more than 80 characters long).

2020-10-02 19:56 UTC, 17cupsofcoffee commented on content/posts/newsletter-014/index.md
> +The initial release version `0.1.0`provides basic recording and playback support for all available backends, including a small music player example!
```suggestion
The initial release version `0.1.0` provides basic recording and playback support for all available backends, including a small music player example!
```

2020-10-03 09:59 UTC, msiglreith commented
Thanks for reviewing!

2020-10-03 13:43 UTC, 17cupsofcoffee approved these changes
Perfect, thanks for amending!

2020-10-04 16:08 UTC, ozkriff approved these changes
:rocket:

2020-10-04 16:09 UTC, merged

2020-10-04 16:09 UTC, ozkriff commented
Awesome, merged!