N14: Recall Singularity
rust-gamedev/rust-gamedev.github.io pull request #305
Opened 2020-10-05 15:33 UTC by AngelOnFira

#278 :tada:

2020-10-05 19:10 UTC, Terkwood approved these changes

2020-10-06 11:44 UTC, 17cupsofcoffee requested changes
Content looks good, just a few issues with formatting and links.

2020-10-06 11:44 UTC, 17cupsofcoffee commented on content/posts/newsletter-014/index.md
> +selection of modules_
```suggestion
![Demo of the basic ship collision](recall_singularity.png)
_A ray-traced selection of modules_
```

2020-10-06 11:44 UTC, 17cupsofcoffee commented on content/posts/newsletter-014/index.md
> +stations created by [Tom Leys][Tom Leys]. This month a new devlog was posted:
```suggestion
stations created by [Tom Leys]. This month a new devlog was posted:
```

2020-10-06 11:44 UTC, 17cupsofcoffee commented on content/posts/newsletter-014/index.md
> +https://medium.com/@recallsingularity/recall-singularity-in-sep-2020-e2f33a85fd7c
```suggestion
[Tom Leys]: https://twitter.com/RecallSingular1
[recall-s-sept-text]: https://medium.com/@recallsingularity/recall-singularity-in-sep-2020-e2f33a85fd7c
```

2020-10-06 13:53 UTC, ozkriff commented
🚧

2020-10-06 14:36 UTC, ozkriff approved these changes
:rocket: (optimized the image and made a few style/wording tweaks)

2020-10-06 14:37 UTC, 17cupsofcoffee approved these changes
🚀

2020-10-06 14:43 UTC, merged