N15: Add Worship The Sun
rust-gamedev/rust-gamedev.github.io pull request #325
Opened 2020-11-02 01:21 UTC by tuzz

Part of #320 ("Newsletter 15")

2020-11-02 09:28 UTC, 17cupsofcoffee requested changes
Content looks good, just a couple of things to tweak.

2020-11-02 09:28 UTC, 17cupsofcoffee commented on content/posts/newsletter-015/index.md
> +_▲ One of the many unique and confounding puzzles in the game_
Not sure if the arrow is necessary here, as the website applies formatting to the image captions to make it more obvious they're connected to the image.

2020-11-02 09:28 UTC, 17cupsofcoffee commented on content/posts/newsletter-015/index.md
> +[/r/WorshipTheSunGame](https://reddit.com/r/WorshipTheSunGame)
This is missing a `_` to close off the italics:
```suggestion
[/r/WorshipTheSunGame](https://reddit.com/r/WorshipTheSunGame)_
```

2020-11-02 09:58 UTC, tuzz commented
Thanks @17cupsofcoffee, both those things are now fixed.

2020-11-02 10:13 UTC, 17cupsofcoffee approved these changes

2020-11-03 17:57 UTC, ozkriff approved these changes
:rocket: (made a few small style/fmt tweaks for consistency with the rest of the newsletter)

2020-11-03 17:57 UTC, merged

2020-11-03 17:58 UTC, ozkriff commented
Thanks for the PR! Good luck with the game :)