N16: Profiling
rust-gamedev/rust-gamedev.github.io pull request #371
Opened 2020-12-01 07:37 UTC by aclysma

2020-12-01 07:38 UTC, aclysma commented
#365

2020-12-01 10:23 UTC, 17cupsofcoffee requested changes
Content looks good :+1: Just a couple of things tripping up the CI build:

```
content/posts/newsletter-016/index.md:72:83 MD009/no-trailing-spaces Trailing spaces [Expected: 0 or 2; Actual: 1]
content/posts/newsletter-016/index.md:72:81 MD013/line-length Line length [Expected: 80; Actual: 83]
content/posts/newsletter-016/index.md:73:81 MD013/line-length Line length [Expected: 80; Actual: 84]
```

2020-12-01 17:03 UTC, 17cupsofcoffee approved these changes

2020-12-04 21:34 UTC, ozkriff approved these changes

2020-12-04 21:35 UTC, merged

2020-12-04 21:35 UTC, ozkriff commented
Merged, thanks!