N16: FBSim release and tutorial
rust-gamedev/rust-gamedev.github.io pull request #377
Opened 2020-12-01 23:12 UTC by IanTayler

Part of #365 

First contribution to the newsletter, so let me know of any potential improvements to the text or PR.

2020-12-02 14:57 UTC, 17cupsofcoffee requested changes
Content looks good, just one formatting thing that's tripping up the CI.

2020-12-02 14:57 UTC, 17cupsofcoffee commented on content/posts/newsletter-016/index.md
> +
```suggestion

```

2020-12-03 00:16 UTC, 17cupsofcoffee approved these changes

2020-12-05 10:24 UTC, ozkriff approved these changes
:fire:

2020-12-05 10:26 UTC, merged

2020-12-05 10:27 UTC, ozkriff commented
Thanks!