N16: ggez
rust-gamedev/rust-gamedev.github.io pull request #385
Opened 2020-12-02 19:29 UTC by icefoxen

What the heck, I have no idea why this is dragging a bunch of other commits with it.  I nuked and re-made my fork and branch from this repo and it's still doing it.

It's been one of those days.

2020-12-02 19:37 UTC, 17cupsofcoffee requested changes
I have *no* clue how this branch has gotten itself so confused - should be able to just cherry pick it to merge though, so not the end of the world 😄 

Text looks good to me, just one minor formatting thing that's tripping up the linter:

2020-12-02 19:37 UTC, 17cupsofcoffee commented on content/posts/newsletter-016/index.md
> + * A bunch of old issues have been cleaned up
```suggestion
- All major dependencies have been updated, including a long-overdue
  update to `winit` 0.23
- Over a dozen pull requests have been merged, large and small
- A bunch of old issues have been cleaned up
```

2020-12-03 03:15 UTC, 17cupsofcoffee approved these changes

2020-12-06 15:33 UTC, ozkriff approved these changes
:+1: (made a few small style/fmt tweaks)

2020-12-06 15:46 UTC, merged

2020-12-06 15:48 UTC, ozkriff commented
Thanks, merged!

As for the other commits - force pushing the `source` branch from the upstream repo to your fork's `source` should help.