N17: Egui
rust-gamedev/rust-gamedev.github.io pull request #415
Opened 2021-01-04 22:31 UTC by emilk

Part of #408

2021-01-05 13:56 UTC, 17cupsofcoffee requested changes
Content looks good, just one error on the CI build:
```
content/posts/newsletter-017/index.md:112:81 MD013/line-length Line length [Expected: 80; Actual: 131]
```

2021-01-05 17:15 UTC, 17cupsofcoffee approved these changes
:+1: LGTM

2021-01-08 12:12 UTC, ozkriff approved these changes

2021-01-08 12:29 UTC, merged

2021-01-08 12:29 UTC, ozkriff commented
Merged, thanks!