N17: Undergrad Thesis on game scripting for legion
rust-gamedev/rust-gamedev.github.io pull request #425
Opened 2021-01-05 23:32 UTC by pablodiegoss

Our section of #408 :D

2021-01-06 00:07 UTC, 17cupsofcoffee requested changes
Looks good, just a few minor formatting things:

2021-01-06 00:07 UTC, 17cupsofcoffee commented on content/posts/newsletter-017/index.md
> +In december 2020, [@pablodiegoss] and [@rodrigocam] presented their undergrad
```suggestion
In December 2020, [@pablodiegoss] and [@rodrigocam] presented their undergrad
```

2021-01-06 00:07 UTC, 17cupsofcoffee commented on content/posts/newsletter-017/index.md
> +, called [Legion Script]. Legion is being currently integrated into the
```suggestion
thesis where they created a proof-of-concept scripting system for the Legion ECS,
called [Legion Script]. Legion is being currently integrated into the
```

2021-01-07 14:30 UTC, pablodiegoss commented
> Looks good, just a few minor formatting things:

Awesome, I've just incorporated that feedback, thanks! :D

2021-01-07 14:41 UTC, 17cupsofcoffee approved these changes

2021-01-12 16:18 UTC, ozkriff commented
Made a few style & fmt changes for consistency with the rest of the newsletter. Also, reworded the link to the forum thread.

@pablodiegoss and @rodrigocam are you ok with these changes?

2021-01-12 16:28 UTC, rodrigocam commented
It seems great to me!

2021-01-12 16:32 UTC, ozkriff approved these changes

2021-01-12 16:34 UTC, merged

2021-01-12 16:35 UTC, ozkriff commented
Thanks for the PR! Good luck with the upcoming blog posts!