N17: Shotcaller
rust-gamedev/rust-gamedev.github.io pull request #431
Opened 2021-01-06 10:36 UTC by erlend-sh

#408

2021-01-06 13:54 UTC, 17cupsofcoffee requested changes
Content looks good, the CI is just complaining about the extra line breaks above the post:
```
content/posts/newsletter-017/index.md:88 MD012/no-multiple-blanks Multiple consecutive blank lines [Expected: 1; Actual: 2]
content/posts/newsletter-017/index.md:89 MD012/no-multiple-blanks Multiple consecutive blank lines [Expected: 1; Actual: 3]
```

2021-01-06 18:35 UTC, mvlabat commented on content/posts/newsletter-017/index.md
> +![Shotcaller dual frontend](/Users/erlend/Documents/GitHub/rust-gamedev.github.io/content/posts/newsletter-016/shotcaller-2guis.png)
The image should also be added to the repo

2021-01-12 20:46 UTC, ozkriff commented
:construction:

2021-01-12 22:15 UTC, ozkriff approved these changes
:+1: (inlined the image and made a few style tweaks)

2021-01-12 23:28 UTC, ozkriff commented
@17cupsofcoffee re-r?

2021-01-12 23:49 UTC, 17cupsofcoffee approved these changes

2021-01-12 23:54 UTC, merged

2021-01-12 23:54 UTC, ozkriff commented
Thanks for the PR!