N17: Thermite
rust-gamedev/rust-gamedev.github.io pull request #442
Opened 2021-01-08 13:14 UTC by AngelOnFira

For #408 :rocket:

2021-01-08 15:02 UTC, 17cupsofcoffee requested changes
Looks good, just a small typo:

2021-01-08 15:02 UTC, 17cupsofcoffee commented on content/posts/newsletter-017/index.md
> +### [Termite SIMD]: Melt Your CPU
```suggestion
### [Thermite SIMD]: Melt Your CPU
```

2021-01-08 15:02 UTC, 17cupsofcoffee commented on content/posts/newsletter-017/index.md
> +[Termite SIMD]: https://github.com/raygon-renderer/thermite
```suggestion
[Thermite SIMD]: https://github.com/raygon-renderer/thermite
```

2021-01-08 15:10 UTC, AngelOnFira commented on content/posts/newsletter-017/index.md
> +[Termite SIMD]: https://github.com/raygon-renderer/thermite
Thanks :sweat_smile:

2021-01-12 23:50 UTC, 17cupsofcoffee approved these changes

2021-01-13 10:13 UTC, ozkriff approved these changes
:+1:

2021-01-13 10:16 UTC, merged

2021-01-13 10:16 UTC, ozkriff commented
^ @novacrazy jfyi

2021-01-13 13:51 UTC, novacrazy commented
Looks good to me, thanks!