N17: rg3d
rust-gamedev/rust-gamedev.github.io pull request #444
Opened 2021-01-10 18:29 UTC by mrDIMAS

For #408

2021-01-11 08:28 UTC, Uriopass requested changes

2021-01-11 08:28 UTC, Uriopass commented on content/posts/newsletter-017/index.md
> +_A level made in [rusty-editor][rusty_editor] which a native scene editor for rg3d game engine._
Please use less than 80 characters per line

2021-01-11 08:28 UTC, Uriopass commented on content/posts/newsletter-017/index.md
> +- rusty-editor now has [navigation meshes][rusty_editor_navmesh] and particle systems editor
Here too

2021-01-13 10:09 UTC, ozkriff approved these changes
:fire:

2021-01-13 10:11 UTC, merged

2021-01-13 10:11 UTC, ozkriff commented
Thanks for the PR!