N19: Bevy Rhythm Game tutorial
rust-gamedev/rust-gamedev.github.io pull request #518
Opened 2021-03-05 18:14 UTC by guimcaballero

Part of #496

2021-03-05 18:17 UTC, 17cupsofcoffee requested changes
Content looks good, just a couple of linter issues:
```
content/posts/newsletter-019/index.md:149:75 MD009/no-trailing-spaces Trailing spaces [Expected: 0 or 2; Actual: 1]
content/posts/newsletter-019/index.md:150:75 MD009/no-trailing-spaces Trailing spaces [Expected: 0 or 2; Actual: 1]
```

2021-03-05 18:29 UTC, 17cupsofcoffee approved these changes

2021-03-06 10:56 UTC, ozkriff approved these changes
:+1:

2021-03-06 10:57 UTC, merged

2021-03-06 10:57 UTC, ozkriff commented
Thanks for the PR!