N22: Nestadia
rust-gamedev/rust-gamedev.github.io pull request #644
Opened 2021-06-02 01:11 UTC by zer0x64

_Part of #640

2021-06-02 01:47 UTC, AngelOnFira commented on content/news/022/index.md
> -
Looks like there was a formatting mistake here

2021-06-02 01:48 UTC, AngelOnFira commented on content/news/022/index.md
> +![Zelda running on Nestadia](img)
I think the image link is messed up?

2021-06-02 01:49 UTC, AngelOnFira commented on content/news/022/index.md
> +[Nestadia] ([https://github.com/zer0x64/nestadia]) by [@zer0x64], [@junior-n30] and [@CBenoit]
You should be fine removing the printed link

2021-06-02 01:51 UTC, AngelOnFira commented on content/news/022/index.md
> +arbitrary code inside a provided ROM.
I think this paragraph might be better split up into two sentences.

`... a cybersecurity competition. Contestants were required to reverse-engineer ...`

2021-06-02 01:53 UTC, AngelOnFira commented on content/news/022/index.md
> +and open-sourced. The developers intend on fixing more bugs
I think this would be more readable like this:

`After the competition, the code was open-sourced and cleaned up to remove references to the competition.`

2021-06-02 01:54 UTC, AngelOnFira commented on content/news/022/index.md
> +anywhere without much work.
Some grammar and wording changes here:

`Some interesting features of this emulator are its server-based nature, and the no_std core which means that the emulator can be built and ran pretty much anywhere without much work.`

2021-06-02 01:55 UTC, AngelOnFira commented on content/news/022/index.md
> +native GUI and debugger.
A few more grammar changes:

`Incoming improvements include online multiplayer, sound, a WASM port, porting to a libretro core, and using wgpu instead of sdl for the native GUI and debugger.`

2021-06-02 01:56 UTC, AngelOnFira requested changes
Great writeup :smile: a few changes needed, but otherwise this should be good :100:

2021-06-02 22:26 UTC, zer0x64 commented
Sorry if the english is kinda broken at some places, it's my second language :upside_down_face:

I've fixed your comments and pushed them!

2021-06-04 13:04 UTC, AngelOnFira commented
Awesome, looks good :smile: There are a few linting issues, but I've submitted a PR to your fork with fixes for them.

https://github.com/zer0x64/rust-gamedev.github.io/pull/1

2021-06-04 13:25 UTC, zer0x64 commented
I just merged your PR!

2021-06-04 13:42 UTC, AngelOnFira approved these changes

2021-06-04 13:42 UTC, merged