N25 - What's the word
rust-gamedev/rust-gamedev.github.io pull request #760
Opened 2021-09-03 09:47 UTC by Vrixyz

_Part of #751_

2021-09-04 16:26 UTC, AngelOnFira commented
I'm wondering if we can add in a gif of it running. Something along these lines:

https://user-images.githubusercontent.com/14791619/132101588-84e9953f-7870-43e3-ab25-ebcb9e2bc44b.mp4

2021-09-04 16:29 UTC, AngelOnFira requested changes

2021-09-04 16:29 UTC, AngelOnFira commented on content/news/025/index.md
> +It's at the prototype stage, let it demonstrate how *small* you can scope your project for a game jam !
```suggestion
A UI-based game in which you tap (or miss) buttons. It was created with <something>. It's at the prototype stage, but can demonstrate how *small* you can scope your project for a game jam!
```

2021-09-04 16:29 UTC, AngelOnFira commented on content/news/025/index.md
> +It's at the prototype stage, let it demonstrate how *small* you can scope your project for a game jam !
It would be cool to hear a bit about what tools were used to create it :)

2021-09-05 01:30 UTC, Vrixyz commented
I'd love to add such a gif! I recorded that during development: https://media.discordapp.net/attachments/879816235133575178/879847235578376233/moving_illusion.mov

Your gif has less height so it might be more fitting though !

I'm currently without computer so I might have difficulties adding that gif and resolve conflicts... So feel free to make final edits ; I can try to make them but I'm sorry I can't promise I'll be able to.

2021-09-08 02:34 UTC, merged