N27: graph game
rust-gamedev/rust-gamedev.github.io pull request #820
Opened 2021-10-31 20:32 UTC by Vrixyz

_Part of #818_

2021-10-31 20:35 UTC, Vrixyz commented
I’ll clean up the lints when I can 🤞

2021-11-01 10:27 UTC, 17cupsofcoffee requested changes
The content looks good, but I think you've put the section in the table of contents rather than under the actual 'Game Updates' heading - could you move it down?

2021-11-01 17:07 UTC, Vrixyz commented
Thanks, should be fixed now 🙏🏼

2021-11-01 17:34 UTC, 17cupsofcoffee approved these changes
🚧 Just making some tweaks to match the style of other sections, looks good though!

2021-11-01 17:34 UTC, 17cupsofcoffee commented on content/news/027/index.md
> +
```suggestion
### [Graph Game]

![image/gameplay of the game: circle and triangles](graph_game.gif)
_Navigating the graph map can be stressful_

[Graph Game] ([GitHub][graph-game-github])
uses [Bevy](https://bevyengine.org/) as its engine. You can play it from your
[browser](https://vrixyz.github.io/graph_nav/) - click on colored triangles,
guess the rules and survive as long as possible!

Development has just begun, and the future of the project is not clear -
the developer welcomes you to come and discuss next steps on the game's
[Discord server][graph-game-discord].

[Graph Game]: https://vrixyz.github.io/graph_nav/
[graph-game-github]: https://github.com/Vrixyz/graph_nav
[graph-game-discord]: https://discord.gg/ZeRkj8pD4n
```

2021-11-01 17:35 UTC, 17cupsofcoffee commented on content/news/027/index.md
>  ## Engine Updates
```suggestion
[graph-game-discord]: https://discord.gg/ZeRkj8pD4n

## Engine Updates
```

2021-11-01 17:50 UTC, merged