N27 - godot-rust
rust-gamedev/rust-gamedev.github.io pull request #829
Opened 2021-11-02 13:32 UTC by jacobsky

Part of #818

2021-11-03 18:34 UTC, 17cupsofcoffee commented on content/news/027/index.md
> +### [godot-rust](https://github.com/godot-rust/godot-rust)
```suggestion
### [godot-rust](https://github.com/godot-rust/godot-rust)
```

2021-11-03 18:34 UTC, 17cupsofcoffee commented on content/news/027/index.md
> +(thanks to chitoyuu for the PR)
```suggestion
(thanks to chitoyuu for the PR).
```

2021-11-03 18:34 UTC, 17cupsofcoffee commented on content/news/027/index.md
> +
```suggestion

```

2021-11-03 18:35 UTC, 17cupsofcoffee commented on content/news/027/index.md
> +[gd-async]: https://github.com/godot-rust/godot-rust/pull/804
```suggestion
to include it.

[gd-async]: https://github.com/godot-rust/godot-rust/pull/804
```

2021-11-03 18:37 UTC, 17cupsofcoffee requested changes
The content looks good, but several of the links are broken/missing URLs - can you add these?

2021-11-04 05:02 UTC, jacobsky commented
@17cupsofcoffee Thank you for the review. Apologies for the missing links, I didn't see those when I was initially previewing the file. It is is fixed in my latest commit.

2021-11-04 09:41 UTC, 17cupsofcoffee approved these changes

2021-11-04 19:25 UTC, merged