N28: FishFight
rust-gamedev/rust-gamedev.github.io pull request #859
Opened 2021-12-02 18:38 UTC by not-fl3

Part of #852

2021-12-02 21:17 UTC, 17cupsofcoffee requested changes
The content looks good (made a couple of tweaks but nothing major), but the GIF is over our 2.5MB limit - could you replace it with a smaller version?

I had a go at optimizing it but I could only get it down to 2.45MB - if you have any bright ideas to shrink it more, then that'd be useful, but if not feel free to use my version:

![fishfight(1)](https://user-images.githubusercontent.com/784533/144504388-d88d04cc-713b-45ab-b8b8-27a7db686af2.gif)

2021-12-02 21:17 UTC, 17cupsofcoffee commented on content/news/028/index.md
> +This month it got the trailer and the game is now available to
```suggestion
This month it got a trailer, and the game is now available to
```

2021-12-02 21:17 UTC, 17cupsofcoffee commented on content/news/028/index.md
> +wishlist on [steam][fishfight-steam]!
```suggestion
wishlist on [Steam][fishfight-steam]!
```

2021-12-02 21:17 UTC, 17cupsofcoffee commented on content/news/028/index.md
> +### [Fish Fight: The Prequel][]
```suggestion
### [Fish Fight: The Prequel][fishfight-steam]
```

2021-12-03 00:44 UTC, not-fl3 commented
Your optimized GIF looks perfect, updated the PR! 

Thanks a lot!

2021-12-03 09:43 UTC, 17cupsofcoffee approved these changes

2021-12-04 18:15 UTC, merged