N28: country-slice
rust-gamedev/rust-gamedev.github.io pull request #861
Opened 2021-12-03 07:28 UTC by anopara

_Part of #852_

2021-12-04 18:19 UTC, AngelOnFira requested changes

2021-12-04 18:19 UTC, AngelOnFira commented on content/news/028/index.md
> +Country Slice uses [Bevy Engine](https://github.com/bevyengine/bevy) for entity management, and has recently [been ported to OpenGL](https://twitter.com/anastasiaopara/status/1464304076074672144?s=20
For any links you have, can you extract them to the bottom?

Example: https://github.com/rust-gamedev/rust-gamedev.github.io/pull/860/files

2021-12-04 18:22 UTC, AngelOnFira commented
Also looks like there may be some linting issues :)

2021-12-04 18:49 UTC, anopara commented
Updated the links & broke down the lines (I think it should be <80 chars now 😅)

2021-12-04 20:41 UTC, AngelOnFira commented
Oh wow! I didn't actually load the page yet, but I was very impressed by this project when I saw it on Twitter. Big fan of your work, I loved the texture synthesis posts you've written. Please keep adding content to the newsletter in the future! :smile:

2021-12-04 20:43 UTC, AngelOnFira approved these changes

2021-12-04 20:48 UTC, merged

2021-12-05 06:34 UTC, anopara commented
Thank you @AngelOnFira 😃