N28: Bendyworm
rust-gamedev/rust-gamedev.github.io pull request #862
Opened 2021-12-03 11:19 UTC by Bauxitedev

I'd like to add Bendyworm to the newsletter.

#852

2021-12-04 18:21 UTC, AngelOnFira requested changes

2021-12-04 18:21 UTC, AngelOnFira commented on content/news/028/index.md
> +level. Why? Because you're inside of a gigantic worm, and worms are bendy.
Can you extract all links to the bottom? I see that some are, but not all.

Example: https://github.com/rust-gamedev/rust-gamedev.github.io/pull/860/files

2021-12-05 10:27 UTC, Bauxitedev commented
I've moved the links to the bottom.

2021-12-05 14:44 UTC, ozkriff approved these changes

2021-12-05 17:08 UTC, AngelOnFira approved these changes

2021-12-05 17:08 UTC, merged