N29: Fish Fight
rust-gamedev/rust-gamedev.github.io pull request #897
Opened 2022-01-07 16:08 UTC by erlend-sh

_Part of #888_

2022-01-09 02:52 UTC, AngelOnFira requested changes
Image is a bit too large, converting to jpg should do the trick 👍

2022-01-09 02:52 UTC, AngelOnFira commented on content/news/029/index.md
> +A retrospective devlog was posted: [Fish Fight's past, present and future][fish-announce]
```suggestion
A retrospective devlog was posted: [Fish Fight's past, present, and future][fish-announce].
```

2022-01-11 19:25 UTC, erlend-sh commented
Converted to JPG. I dunno how to get this PR resolved now though. Maybe I should just open a new one..

2022-01-11 19:38 UTC, AngelOnFira commented
I you create another commit where you delete the image, it will be fine since the commits get squashed :) Although the image is still a bit large. I can make a commit that cleans this up :)

2022-01-11 19:42 UTC, AngelOnFira approved these changes

2022-01-11 20:02 UTC, 17cupsofcoffee approved these changes

2022-01-11 20:02 UTC, 17cupsofcoffee commented on content/news/029/index.md
> +[website][fish-website])
```suggestion
[website][fish-website])
```

2022-01-11 20:14 UTC, erlend-sh commented
Thanks for the assist! 🙏 ❤️

2022-01-11 20:48 UTC, ozkriff approved these changes

2022-01-11 20:48 UTC, merged

2022-01-11 20:48 UTC, ozkriff commented
Thanks for the PR!