N30: add leafwing-input-manager
rust-gamedev/rust-gamedev.github.io pull request #917
Opened 2022-02-02 04:33 UTC by alice-i-cecile

Part of #912.

2022-02-02 20:16 UTC, 17cupsofcoffee requested changes
Looks good, just a IDE-applied change that needs reverting.

The section is a little short compared to the others in the newsletter - this is fine, but feel free to elaborate on some of your library's features if you want to make use of the extra room!

2022-02-02 20:16 UTC, 17cupsofcoffee commented on content/news/030/index.md
> +  - [leafwing-input-manager](#leafwing-input-manager)
Can you revert this change?

2022-02-02 20:41 UTC, alice-i-cecile commented on content/news/030/index.md
> +  - [leafwing-input-manager](#leafwing-input-manager)
Oops, yep.

2022-02-03 00:15 UTC, 17cupsofcoffee approved these changes

2022-02-03 00:16 UTC, merged