N30: rafx
rust-gamedev/rust-gamedev.github.io pull request #919
Opened 2022-02-02 06:17 UTC by aclysma

Added update for rafx

_Part of #912_

2022-02-02 09:50 UTC, ozkriff approved these changes

2022-02-02 18:14 UTC, 17cupsofcoffee approved these changes

2022-02-02 18:14 UTC, 17cupsofcoffee commented on content/news/030/index.md
> +of shadow-casting lights. It is targetting compute shaders and will be adding
```suggestion
of shadow-casting lights. It is targeting compute shaders and will be adding
```

2022-02-02 18:14 UTC, 17cupsofcoffee commented on content/news/030/index.md
> +of shadow-casting lights. It is targetting compute shaders and will be adding
I can't commit to your branch, can you resolve this before I merge?

2022-02-04 00:14 UTC, 17cupsofcoffee requested changes
This looks ready to go, but I don't have access to the branch to resolve the conflicts myself.

2022-02-04 00:35 UTC, merged

2022-02-04 00:35 UTC, 17cupsofcoffee commented
sneaky manual merge 🥷