N31: Molecoole
rust-gamedev/rust-gamedev.github.io pull request #954
Opened 2022-03-05 13:08 UTC by Hilku

Part of https://github.com/rust-gamedev/rust-gamedev.github.io/issues/949

2022-03-05 13:33 UTC, 17cupsofcoffee approved these changes

2022-03-05 13:33 UTC, 17cupsofcoffee commented on content/news/031/index.md
> +You can check out it's gameplay on [youtube][youtube-molecoole],
```suggestion
You can check out its gameplay on [youtube][youtube-molecoole],
```

2022-03-05 13:33 UTC, 17cupsofcoffee commented on content/news/031/index.md
> +[molecoole-steam]: https://store.steampowered.com/app/1792170/Molecoole/
```suggestion
or on the Steam page. 

[molecoole-steam]: https://store.steampowered.com/app/1792170/Molecoole/
```

2022-03-06 02:26 UTC, 17cupsofcoffee commented on content/news/031/index.md
> +or on the Steam page.
```suggestion
or on the Steam page.
```

2022-03-07 22:48 UTC, AngelOnFira requested changes

2022-03-07 22:48 UTC, AngelOnFira commented on content/news/031/index.md
> +Engine](https://github.com/bevyengine/bevy).
Please move links to the bottom :)

2022-03-08 00:48 UTC, AngelOnFira approved these changes

2022-03-08 00:52 UTC, merged