N31: Notan
rust-gamedev/rust-gamedev.github.io pull request #959
Opened 2022-03-06 14:19 UTC by Nazariglez

Hello! This is my write-up about Notan. 

Part of #949 

Let me know if you need anything. Thanks!

2022-03-07 23:01 UTC, AngelOnFira requested changes

2022-03-07 23:01 UTC, AngelOnFira commented on content/news/031/index.md
> +text rendering, and [egui](https://github.com/emilk/egui) integration.
Please move all links to the bottom :)

2022-03-08 00:51 UTC, AngelOnFira approved these changes

2022-03-08 00:53 UTC, merged

2022-03-08 11:25 UTC, Nazariglez commented
Just saw this, thank you for making the changes! I wasn't sure if adding egui to the bottom could be a conflict with another section that uses [egui] on their text. I'll do it right the next time. 

Thanks

2022-03-08 12:11 UTC, AngelOnFira commented
It might, but so far we haven't had too much of an issue with overlap like that :)